file_entity.type.*:
  type: config_entity
  label: 'File type'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
    mimetypes:
      type: sequence
      label: 'MIME types'
      sequence:
        - type: string
          label: 'MIME type'

file_entity.settings:
  type: config_object
  label: 'File Entity settings'
  mapping:
    max_filesize:
      type: integer
      label: 'Maximum upload size'
    default_allowed_extensions:
      type: string
      label: 'Default allowed file extensions'
    alt:
      type: string
      label: 'Alt attribute'
    title:
      type: string
      label: 'Title attribute'
    wizard_skip_file_type:
      type: boolean
      label: 'Skip filetype selection'
    wizard_skip_scheme:
      type: boolean
      label: 'Skip scheme selection'
    wizard_skip_fields:
      type: boolean
      label: 'Skip available fields'
    allow_insecure_download:
      type: boolean
      label: Allow insecure downloads

field.formatter.settings.file_image:
  type: field.formatter.settings.image
  label: 'Image formatter for file entity settings'
  mapping:
    title:
      type: string
      label: 'Title field'
    alt:
      type: string
      label: 'Alt field'

field.formatter.settings.file_size:
  type: mapping

field.formatter.settings.file_download_link:
  type: mapping
  label: 'File download link display format settings'
  mapping:
    access_message:
      type: string
      label: 'Access message'
    text:
      type: string
      label: 'Link text'

field.formatter.settings.file_audio:
  type: mapping
  label: 'File audio display format settings'
  mapping:
    controls:
      type: boolean
      label: 'Show audio controls'
    autoplay:
      type: boolean
      label: 'Autoplay'
    loop:
      type: boolean
      label: 'Loop'
    multiple_file_behavior:
      type: string
      label: 'Display of multiple files'

field.formatter.settings.file_video:
  type: mapping
  label: 'File video display format settings'
  mapping:
    controls:
      type: boolean
      label: 'Show audio controls'
    autoplay:
      type: boolean
      label: 'Autoplay'
    loop:
      type: boolean
      label: 'Loop'
    muted:
      type: boolean
      label: 'Muted'
    width:
      type: integer
      label: 'Width'
    height:
      type: integer
      label: 'Height'
    multiple_file_behavior:
      type: string
      label: 'Display of multiple files'

action.configuration.file_delete_action:
  type: action_configuration_default
  label: 'Delete file configuration'

action.configuration.file_permanent_action:
  type: action_configuration_default
  label: 'Set file to permanent configuration'

action.configuration.file_temporary_action:
  type: action_configuration_default
  label: 'Set file to temporary configuration'

field.widget.settings.file_editable:
  type: field.widget.settings.file_generic
  label: 'File format settings'

views.filter_value.file_entity_type:
  type: sequence
  label: 'Values'
  sequence:
    type: string
    label: 'Value'
