# Schema for configuration files of the ImageWidgetCrop module.

field.widget.settings.image_widget_crop:
  type: mapping
  label: 'Image field display format settings'
  mapping:
    progress_indicator:
      type: string
      label: 'Progress indicator'
    preview_image_style:
      type: string
      label: 'Preview image style'
    crop_preview_image_style:
      type: string
      label: 'Preview crop image style'
    crop_list:
      type: mapping
      label: 'The preview image will be cropped'
    crop_help_text:
      type: string
      label: 'Default help text slide'
