social_feed_fetcher.settings:
   type: config_object
   label: Feed Settings
   mapping:
     fb_page_name:
       type: string
       label: Facebook Page Name
     fb_app_id:
       type: string
       label: Facebook App ID
     fb_secret_key:
       type: string
       label: Facebook Secret Key
     fb_no_feeds:
       type: integer
       label: Number of feeds
     all_types:
       type: boolean
       label: Show all post types
     post_type:
       type: string
       label: Select your post type(s) to show
     display_pic:
       type: boolean
       label: Show Post Picture
     display_video:
       type: boolean
       label: Show Post Video
     trim_length:
       type: integer
       label: Trim Length
     teaser_text:
       type: string
       label: Teaser Text
     hashtag:
       type: boolean
       label: Show Hashtag
     time_stamp:
       type: boolean
       label: Show Date/Time
     time_format:
       type: string
       label: Date/Time format
     tw_consumer_key:
       type: string
       label: Twitter Consumer Key
     tw_consumer_secret:
       type: string
       label: Twitter Consumer Secret
     tw_access_token:
       type: string
       label: Twitter Access Token
     tw_access_token_secret:
       type: string
       label: Twitter Access Token Secret
     tw_count:
       type: integer
       label: Tweets Count
     hashtag:
       type: boolean
       label: Show Hashtag
     time_stamp:
       type: boolean
       label: Show Date/Time
     time_format:
       type: string
       label: Date/Time format
     time_ago:
       type: boolean
       label: Show date Twitter style
     trim_length:
       type: integer
       label: Trim Length
     teaser_text:
       type: string
       label: Teaser Text
     in_client_id:
       type: string
       label: client_id
     in_redirect_uri:
       type: string
       label: Redirect URI
     in_access_token:
       type: string
       label: Access Token
     in_picture_count:
       type: integer
       label: Picture Count
     in_picture_resolution:
       type: string
       label: Picture Resolution
     time_format:
       type: string
       label: Date/Time format
     in_post_link:
       type: boolean
       label: Show post URL