id: ymca_migrate_url_alias_page
label: 'URL aliases'
migration_group: ymca
migration_tags:
  - node
source:
  plugin: ymca_migrate_url_alias_page
process:
  source: source
  alias: alias
  langcode:
    plugin: default_value
    default_value: en
destination:
  plugin: url_alias
migration_dependencies:
  required:
    - ymca_migrate_node_page
