id: ymca_migrate_menu_link_content_kid_teen_activities
label: 'Menu links migration'
migration_group: ymca
migration_tags:
  - menu
source:
  plugin: ymca_migrate_menu_link_content
  constants:
    menu_name: kids-teen-activities
    menu_parents:
      - 4835
process:
  bundle:
    plugin: default_value
    default_value: menu_link_content
  title: title
  menu_name: menu_name
  link: link
  weight: sequence_index
  enabled: enabled
  parent:
    -
      plugin: migration
      migration: ymca_migrate_menu_link_content_kid_teen_activities
      source: parent_id
    -
      plugin: ymca_migrate_menu_link_content_parent
destination:
  plugin: 'entity:menu_link_content'
