id: ymca_migrate_node_blog
label: 'Blog migration.'
migration_group: ymca
migration_tags:
  - node
source:
  plugin: ymca_migrate_node_blog
process:
  type:
    plugin: default_value
    default_value: blog
  title: title
  langcode:
    plugin: default_value
    source: language
    default_value: en
  uid:
    plugin: default_value
    default_value: 1
  sticky:
    plugin: default_value
    default_value: 0
  status:
    plugin: default_value
    default_value: 1
  created:
    plugin: ymca_migrate_date
    source: created_on
  changed:
    plugin: ymca_migrate_date
    source: modified_on
  field_content/value: content
  field_content/format:
    plugin: default_value
    default_value: full_html
  field_summary/value: summary
  field_summary/format:
    plugin: default_value
    default_value: full_html
  field_image/target_id:
    plugin: migration
    migration: ymca_migrate_file_image
    source: image
  field_image/alt: image_alt
  field_tags/target_id:
    plugin: migration
    migration: ymca_migrate_taxonomy_term_tags
    source: label_id
destination:
  plugin: 'entity:node'
migration_dependencies:
  required:
    - ymca_migrate_taxonomy_term_tags
    - ymca_migrate_file_image
    - ymca_migrate_menu_link_content_kid_teen_activities
    - ymca_migrate_menu_link_content_camps
    - ymca_migrate_menu_link_content_child_care_preschool
    - ymca_migrate_menu_link_content_community_programs
    - ymca_migrate_menu_link_content_health_fitness
    - ymca_migrate_menu_link_content_locations
    - ymca_migrate_menu_link_content_main
    - ymca_migrate_menu_link_content_swimming
    - ymca_migrate_menu_link_content_jobs_suppliers_news
