# Schema for the configuration files of the Webform module.

webform.settings:
  type: mapping
  label: 'Webform settings'
  mapping:
    node_types_primary:
      type: array
      label: 'Primary webform node type(s)'
    disabled_components:
      type: array
      label: 'Available components'
    email:
      type: mapping
      label: 'Default e-mail values'
      mapping:
        default_from_address:
          type: string
          label: 'From address'
        default_from_name:
          type: string
          label: 'From name'
        default_subject:
          type: string
          label: 'Default subject'
        replyto:
          type: boolean
          label: 'Use Reply-To header'
        html_capable:
          type: boolean
          label: 'HTML capable mail system'
        default_format:
          type: integer
          label: 'Format'
        format_override:
          type: integer
          label: 'Format override'
    progressbar:
      type: mapping
      label: 'Progress bar'
      mapping:
        style:
          type: array
          label: 'Progress bar style'
        label_first:
          type: string
          label: 'First page label'
        label_confirmation:
          type: string
          label: 'Confirmation page label'
    advanced:
      type: mapping
      label: 'Advanced options'
      mapping:
        tracking_mode:
          type: string
          label: 'Track anonymous users by'
        email_address_format:
          type: string
          label: 'E-mail address format'
        email_address_individual:
          type: integer
          label: 'E-mailing multiple recipients'
        date_type:
          type: string
          label: 'Date format'
        export_format:
          type: string
          label: 'Default export format'
        csv_delimiter:
          type: string
          label: 'Default export delimiter'
        export_wordwrap:
          type: integer
          label: 'Word-wrap all exported text'
        excel_legacy_exporter:
          type: boolean
          label: 'Legacy Excel exporter enabled'
        submission_access_control:
          type: integer
          label: 'Submission access control'
        email_select_max:
          type: integer
          label: 'E-mail mapping limit'
    allowed_tags:
      type: array
      label: 'Allowed HTML tags for XSS checks'
    update_batch_size:
      type: integer
      label: 'Update batch size'
    export_path:
      type: string
      label: 'Export path'
    table:
      type: boolean
      label: 'Enable table listings'
