rabbit_hole.behavior_settings.*:
  type: config_entity
  label: 'Behavior settings config'
  mapping:
    id:
      type: string
      label: 'ID'
    uuid:
      type: string
    action:
      type: string
      label: 'Action'
    allow_override:
      type: integer
      label: 'Allow override'
    redirect:
      type: string
      label: 'Redirect path'
    redirect_code:
      type: integer
      label: 'Redirect code'
