---
env:
  pre_settings:
    - { name: '$settings["hash_salt"]', status: true, value: '1N26qj6mgJF6BpGU_Flo4SLiA72DCZMRd-WkCInvTd3VumZoxvGK_torzbh6JgHg010jkiL3HQ'}
    - { name: '$databases["amm_source"]["default"]["database"]', status: true, value: '{{ old_source_db_name }}' }
    - { name: '$databases["amm_source"]["default"]["username"]', status: true, value: 'root' }
    - { name: '$databases["amm_source"]["default"]["password"]', status: true, value: 'root' }
    - { name: '$databases["amm_source"]["default"]["host"]', status: true, value: '127.0.0.1' }
    - { name: '$databases["amm_source"]["default"]["namespace"]', status: true, value: 'Drupal\\\\Core\\\\Database\\\\Driver\\\\mysql' }
    - { name: '$databases["amm_source"]["default"]["driver"]', status: true, value: 'mysql' }
    - { name: '$config_directories["staging"]', status: true, value: 'sites/default/config/staging' }
    - { name: '$settings["install_profile"]', status: true, value: 'pp' }
  modules:
    - { name: 'devel config_inspector dblog stage_file_proxy', status: true }
  drush_commands:
    - { name: 'user-password', status: true, arguments: "{{ drupal_user }} --password={{ drupal_pass }}" }
    - { name: 'config-set', status: true, arguments: "system.site uuid 97eff2a4-ba00-4bd3-b64c-7641d6ccb54c -y" }
    - { name: 'config-set', status: true, arguments: "system.file path.temporary /tmp -y" }
    - { name: 'config-set', status: true, arguments: "mailsystem.settings defaults.sender php_mail" }
    - { name: 'config-set', status: true, arguments: "smtp.settings smtp_on 1" }
    - { name: 'config-import', status: false, arguments: "staging -y --partial" }
    - { name: 'cr', status: false, arguments: "" }
    - { name: 'ciboxcr', status: true, arguments: "" }
    - { name: 'migrate-import', status: false, arguments: "--group=ymca --force" }
    - { name: 'search-api-reindex', status: false, arguments: "" }
    - { name: 'search-api-index', status: false, arguments: "" }
    - { name: 'search-index', status: false, arguments: "" }
    - { name: 'config-set', status: true, arguments: "shield.config enabled 1" }
    - { name: 'config-set', status: true, arguments: "ymca_google.settings is_production 0" }
    # Set active configuration for specific environment.
    - { name: 'php-eval', status: false, arguments: "\"\\Drupal::service('environment_config.handler')->setActiveConfig('ymca_mindbody.trainings_mapping', 'staging');\"" }
    - { name: 'php-eval', status: false, arguments: "\"\\Drupal::service('environment_config.handler')->setActiveConfig('mindbody.settings', 'staging');\"" }
    - { name: 'php-eval', status: true, arguments: "\"\\Drupal::service('environment_config.handler')->setActiveConfig('ymca_site_verify.settings', 'staging');\"" }
    - { name: 'php-eval', status: true, arguments: "\"\\Drupal::service('environment_config.handler')->setActiveConfig('google_tag.settings', 'staging');\"" }
    # To fix configuration problem let's install the module here.
    - { name: 'en', status: true, arguments: "yptf_master" }
    # Configure synchroniation.
    - { name: 'php-eval', status: true, arguments: "\"\\Drupal::configFactory()->getEditable('ymca_sync.settings')->set('active_syncers', ['personify_mindbody_sync.syncer_fast', 'ymca_google.syncer'])->save(TRUE);\"" }
    - { name: 'php-eval', status: true, arguments: "\"\\Drupal::configFactory()->getEditable('personify_mindbody_sync.settings')->set('is_production', '0')->save(TRUE);\"" }
    - { name: 'php-eval', status: true, arguments: "\"\\Drupal::configFactory()->getEditable('ymca_personify.settings')->set('customer_orders_endpoint', 'http://ygtctrain2.personifycloud.com/personifydataservices/PersonifyData.svc/CL_MindBodyCustomerOrder')->save(TRUE);\"" }
    - { name: 'php-eval', status: true, arguments: "\"\\Drupal::configFactory()->getEditable('ymca_personify.settings')->set('customer_orders_username', 'Alex.Schedrov')->save(TRUE);\"" }
    - { name: 'php-eval', status: true, arguments: "\"\\Drupal::configFactory()->getEditable('ymca_personify.settings')->set('customer_orders_password', 'A!ex!23')->save(TRUE);\"" }
  post_settings:
    - { name: '$settings["cache"]["bins"]["render"]', status: false, value: 'cache.backend.memory' }
    - { name: '$config["stage_file_proxy.settings"]["origin"]', status: true, value: '{{ origin_site_url }}' }

