---
env:
  pre_settings:
    - { name: '$settings["hash_salt"]', status: true, value: '1N26qj6mgJF6BpGU_Flo4SLiA72DCZMRd-WkCInvTd3VumZoxvGK_torzbh6JgHg010jkiL3HQ'}
    - { name: '$databases["amm_source"]["default"]["database"]', status: true, value: '{{ old_source_db_name }}' }
    - { name: '$databases["amm_source"]["default"]["username"]', status: true, value: 'root' }
    - { name: '$databases["amm_source"]["default"]["password"]', status: true, value: 'root' }
    - { name: '$databases["amm_source"]["default"]["host"]', status: true, value: '127.0.0.1' }
    - { name: '$databases["amm_source"]["default"]["namespace"]', status: true, value: 'Drupal\\\\Core\\\\Database\\\\Driver\\\\mysql' }
    - { name: '$databases["amm_source"]["default"]["driver"]', status: true, value: 'mysql' }
    - { name: '$config_directories["staging"]', status: true, value: 'sites/default/config/staging' }
    - { name: '$config_directories["sync"]', status: true, value: 'sites/default/config/staging' }
    - { name: '$settings["install_profile"]', status: true, value: 'openy' }
    - { name: '$config["system.file"]["path"]["temporary"]', status: true, value: '/tmp' }
    - { name: '$settings["memcache"]["bins"]', status: false, value: '[\\"default\\" => \\"default\\"]' }
    - { name: '$settings["memcache"]["key_prefix"]', status: false, value: '{{ mysql_db }}' }
    - { name: '$settings["cache"]["default"]', status: false, value: 'cache.backend.memcache' }
  pre_drush_commands:
    - { name: 'php-eval', status: false, arguments: "\"\\Drupal::keyValue('system.schema')->set('ymca_master', 8259);\"" }
  shell_commands:
    # @todo Remove after OpenY Migration.
    - { name: '[Openy Migrate] Updating OpenY', status: false, arguments: "echo system serialization syslog file node rest entity_browser file_browser dropzonejs openy | xargs -n 1 | xargs -I item bin/drupal update:execute item"}
    - { name: '[Openy Migrate] Updating YMCA Master specific updates', status: false, arguments: "echo 8234 8235 8236 8237 | xargs -n 1 | xargs -I item bin/drupal update:execute ymca_master item"}
    - { name: '[Openy Migrate] Updating YMCA Master specific updates', status: false, arguments: "echo 8238 8239 8240 8241 8242 8243 | xargs -n 1 | xargs -I item bin/drupal update:execute ymca_master item"}
    - { name: '[Openy Migrate] Updating YMCA Master specific updates', status: false, arguments: "echo 8244 8245 8246 8247 8248 8249 8250 8251 | xargs -n 1 | xargs -I item bin/drupal update:execute ymca_master item"}
    - { name: '[Openy Migrate] Updating YMCA Master specific updates', status: false, arguments: "echo 8258 | xargs -n 1 | xargs -I item bin/drupal update:execute ymca_master item"}
    - { name: '[Openy Migrate] Updating OpenY related features', status: false, arguments: "echo webform redirect crop openy_media openy_media_document openy_media_video openy_node openy_node_landing openy_txnm_color openy_prgf_small_banner openy_prgf_simple_content openy_prgf_2c openy_block_custom_simple openy_prgf | xargs -n 1 | xargs -I item bin/drupal update:execute item"}
    - { name: '[Openy Migrate] Updating YMCA Master specific updates', status: false, arguments: "echo 8262 | xargs -n 1 | xargs -I item bin/drupal update:execute ymca_master item"}
    - { name: '[Openy Migrate] Updating YMCA Master remaining updates', status: false, arguments: "bin/drupal update:execute ymca_master"}
  modules:
    - { name: 'dblog stage_file_proxy', status: true }
  drush_commands:
    - { name: 'user-password', status: true, arguments: "{{ drupal_user }} --password={{ drupal_pass }}" }
    - { name: 'config-set', status: true, arguments: "system.site uuid 97eff2a4-ba00-4bd3-b64c-7641d6ccb54c -y" }
    - { name: 'config-set', status: true, arguments: "system.file path.temporary /tmp -y" }
    - { name: 'config-set', status: true, arguments: "mailsystem.settings defaults.sender SMTPMailSystem" }
    - { name: 'config-set', status: true, arguments: "smtp.settings smtp_on 1" }
    - { name: 'config-set', status: true, arguments: "smtp.settings smtp_port 1025" }
    - { name: 'config-set', status: true, arguments: "smtp.settings smtp_protocol standard" }
    - { name: 'config-set', status: true, arguments: "smtp.settings smtp_username ''" }
    - { name: 'config-set', status: true, arguments: "smtp.settings smtp_password ''" }
    - { name: 'config-set', status: true, arguments: "smtp.settings smtp_host ygtc.cibox.tools" }
    - { name: 'config-set', status: true, arguments: "smtp.settings smtp_from from_www_smtp@localhost.com" }
    - { name: 'config-set', status: true, arguments: "smtp.settings smtp_fromname 'Testing Emails'" }
    - { name: 'config-import', status: false, arguments: "staging -y --partial" }
    - { name: 'ciboxcr', status: true, arguments: "" }
    - { name: 'cr', status: true, arguments: "" }
    - { name: 'migrate-import', status: false, arguments: "--group=ymca --force" }
    - { name: 'search-api-reindex', status: false, arguments: "" }
    - { name: 'search-api-index', status: false, arguments: "" }
    - { name: 'search-index', status: false, arguments: "" }
    - { name: 'config-set', status: true, arguments: "shield.config enabled 1" }
    - { name: 'config-set', status: true, arguments: "shield.config login ygtc" }
    - { name: 'config-set', status: true, arguments: "shield.config password openy" }
    # Set active configuration for specific environment.
    - { name: 'php-eval', status: true, arguments: "\"\\Drupal::service('environment_config.handler')->setActiveConfig('ymca_mindbody.trainings_mapping', 'staging');\"" }
    - { name: 'php-eval', status: true, arguments: "\"\\Drupal::service('environment_config.handler')->setActiveConfig('mindbody.settings', 'staging');\"" }
    - { name: 'php-eval', status: true, arguments: "\"\\Drupal::service('environment_config.handler')->setActiveConfig('ymca_site_verify.settings', 'staging');\"" }
    - { name: 'php-eval', status: true, arguments: "\"\\Drupal::service('environment_config.handler')->setActiveConfig('google_tag.settings', 'staging');\"" }
    # To fix configuration problem let's install the module here.
    - { name: 'en', status: false, arguments: "yptf_master" }
    # Configure synchroniation.
    - { name: 'php-eval', status: true, arguments: "\"\\Drupal::configFactory()->getEditable('ymca_sync.settings')->set('active_syncers', ['personify_mindbody_sync.syncer_fast', 'ymca_google.syncer', 'ymca_cdn_sync.syncer'])->save(TRUE);\"" }
    - { name: 'php-eval', status: true, arguments: "\"\\Drupal::configFactory()->getEditable('personify_mindbody_sync.settings')->set('is_production', '0')->save(TRUE);\"" }
    - { name: 'php-eval', status: true, arguments: "\"\\Drupal::configFactory()->getEditable('ymca_personify.settings')->set('customer_orders_endpoint', 'https://account.ymcamn.org/PersonifyDataServices/Personifydata.svc/CL_MindBodyCustomerOrder')->save(TRUE);\"" }
    - { name: 'php-eval', status: true, arguments: "\"\\Drupal::configFactory()->getEditable('ymca_personify.settings')->set('childcare_endpoint', 'https://account.ymcamn.org/PersonifyDataServices/PersonifyData.svc/CL_GetChildcarePayments')->save(TRUE);\"" }
    - { name: 'php-eval', status: true, arguments: "\"\\Drupal::configFactory()->getEditable('ymca_personify.settings')->set('customer_orders_username', 'Paperless.Integratio')->save(TRUE);\"" }
    - { name: 'php-eval', status: true, arguments: "\"\\Drupal::configFactory()->getEditable('ymca_personify.settings')->set('customer_orders_password', 'ymcA9622')->save(TRUE);\"" }
    # Set calendar syncer to test mode.
    - { name: 'config-set', status: true, arguments: "ymca_google.settings is_production 0" }
    # Set MindCacheProxy status endpoint as a secondary.
    - { name: 'config-set', status: false, arguments: "mindbody_cache_proxy.settings primary 0" }
    # Configure Camp du Nord
    - { name: 'php-eval', status: true, arguments: "\"\\Drupal::configFactory()->getEditable('ymca_cdn_sync.settings')->set('data_service_url', 'https://ygtctrain3ebiz.personifycloud.com/PersonifyDataServices/PersonifyData.svc')->save(TRUE);\"" }
    - { name: 'php-eval', status: true, arguments: "\"\\Drupal::configFactory()->getEditable('ymca_cdn_sync.settings')->set('data_service_user', 'FFW17')->save(TRUE);\"" }
    - { name: 'php-eval', status: true, arguments: "\"\\Drupal::configFactory()->getEditable('ymca_cdn_sync.settings')->set('data_service_password', 'Winter2017')->save(TRUE);\"" }
    - { name: 'php-eval', status: true, arguments: "\"\\Drupal::configFactory()->getEditable('ymca_camp_du_nord.settings')->set('wsdl', 'https://ygtctrain3ebiz.personifycloud.com/SSO/webservice/service.asmx?wsdl')->save(TRUE);\"" }
    - { name: 'php-eval', status: true, arguments: "\"\\Drupal::configFactory()->getEditable('ymca_camp_du_nord.settings')->set('url_login', 'https://ygtctrain3ebiz.personifycloud.com/PersonifyEbusiness/Default.aspx?TabID=337')->save(TRUE);\"" }
    - { name: 'php-eval', status: true, arguments: "\"\\Drupal::configFactory()->getEditable('ymca_camp_du_nord.settings')->set('url_account', 'https://ygtctrain3ebiz.personifycloud.com/personifyebusiness/MyY.aspx')->save(TRUE);\"" }
    - { name: 'php-eval', status: true, arguments: "\"\\Drupal::configFactory()->getEditable('ymca_camp_du_nord.settings')->set('url_sign_out', 'https://ygtctrain3ebiz.personifycloud.com/personifyebusiness/MyY/tabid/61/ctl/Logoff/Default.aspx')->save(TRUE);\"" }
    - { name: 'php-eval', status: true, arguments: "\"\\Drupal::configFactory()->getEditable('ymca_camp_du_nord.settings')->set('url_cart', 'https://ygtctrain3ebiz.personifycloud.com/PersonifyEbusiness/YMCA/ShoppingCart.aspx')->save(TRUE);\"" }
  post_settings:
    - { name: '$settings["cache"]["bins"]["render"]', status: false, value: 'cache.backend.memory' }
    - { name: '$config["stage_file_proxy.settings"]["origin"]', status: true, value: '{{ origin_site_url }}' }
