api_url: api.drupal.org
page_alter: false
raw_names: false
error_handlers:
  - '0'
krumo_skin: default
rebuild_theme: false
debug_mail_file_format: '%to-%subject-%datetime.mail.txt'
debug_mail_directory: 'temporary://devel-mails'
