id: ymca_migrate_menu_link_content_redirect
label: 'Menu links migration for the redirects'
migration_group: ymca
migration_tags:
  - menu
source:
  plugin: ymca_migrate_menu_link_content_redirect
process:
  bundle:
    plugin: default_value
    default_value: menu_link_content
  title: title
  menu_name: menu_name
  link: link
  weight: sequence_index
  enabled: enabled
  parent:
    plugin: ymca_migrate_menu_link_content_parent
    source: parent_mlid
destination:
  plugin: 'entity:menu_link_content'
migration_dependencies:
  required:
    - ymca_migrate_menu_link_content_camps
    - ymca_migrate_menu_link_content_child_care_preschool
    - ymca_migrate_menu_link_content_community_programs
    - ymca_migrate_menu_link_content_health_fitness
    - ymca_migrate_menu_link_content_jobs_suppliers_news
    - ymca_migrate_menu_link_content_kid_teen_activities
    - ymca_migrate_menu_link_content_locations
    - ymca_migrate_menu_link_content_main
    - ymca_migrate_menu_link_content_swimming
