locations:
  1:
    label: 'Andover YMCA'
    active: true
  10:
    label: 'Blaisdell YMCA'
    active: true
  11:
    label: 'Burnsville YMCA'
    active: true
  13:
    label: 'Eagan YMCA'
    active: true
  9:
    label: 'Elk River YMCA'
    active: true
  12:
    label: 'Emma B. Howe - Coon Rapids YMCA'
    active: true
  14:
    label: 'Forest Lake YMCA'
    active: true
  6:
    label: 'Hastings YMCA'
    active: true
  23:
    label: 'Heritage Park YMCA'
    active: true
  22:
    label: 'Hudson YMCA'
    active: true
  3:
    label: 'Lino Lakes YMCA'
    active: true
  2:
    label: 'Midway YMCA'
    active: true
  5:
    label: 'Minneapolis Downtown YMCA'
    active: true
  20:
    label: 'New Hope YMCA'
    active: true
  7:
    label: 'Ridgedale YMCA'
    active: true
  8:
    label: 'River Valley YMCA'
    active: true
  19:
    label: 'Shoreview YMCA'
    active: true
  18:
    label: 'Southdale YMCA'
    active: true
  17:
    label: 'St. Paul Downtown YMCA'
    active: true
  24:
    label: 'St. Paul Eastside YMCA'
    active: true
  16:
    label: 'West St. Paul YMCA'
    active: true
  4:
    label: 'White Bear Lake YMCA'
    active: true
  15:
    label: 'Woodbury YMCA'
    active: true
programs:
  2:
    label: 'Personal Training'
    active: true
    image: personal_training.jpg
  3:
    label: 'Internal Staff Appointments'
    active: false
  4:
    label: 'Buddy Training'
    active: true
    image: buddy_training.jpg
  7:
    label: 'Small Group Training'
    active: false
  9:
    label: 'Member Engagements'
    active: false
  11:
    label: 'Metabolic Testing'
    active: false
  12:
    label: 'Private Swim'
    active: false
session_types:
  5:
    label: 'Personal Training - Express - 30 Minutes'
    active: true
  7:
    label: 'Personal Training - Full - 60 Minutes'
    active: true
  55:
    label: 'Promo PT Express'
    active: false
  8:
    label: Lunch
    active: false
  9:
    label: Meeting
    active: false
  32:
    label: 'Training (Professional Development)'
    active: false
  37:
    label: 'Client Management'
    active: false
  48:
    label: 'Reserved (Non Paid)'
    active: false
  17:
    label: 'Group Pilates Reformer'
    active: false
  49:
    label: 'Body Gem (Member)'
    active: false
  50:
    label: 'Body Gem (Non Member)'
    active: false
  11:
    label: 'Buddy Session - Full - 60 Minutes'
    active: true
  12:
    label: 'Buddy Session - Express - 30 Minutes'
    active: true
  21:
    label: 'Personal Consultation'
    active: false
  22:
    label: 'Aqua Consultation'
    active: false
  27:
    label: 'Fitness Assessment'
    active: false
  28:
    label: 'Personal Checkpoint'
    active: false
  29:
    label: 'Equipment Orientation'
    active: false
  30:
    label: 'Youth Orientation 7-9'
    active: false
  31:
    label: 'Youth Orientation 10-11'
    active: false
  46:
    label: 'Youth Orientation 12-14'
    active: false
  47:
    label: 'Youth Orientation 15-17'
    active: false
  74:
    label: 'Active Older Adult Orientation'
    active: false
