crop.type.*:
  type: config_entity
  label: 'Crop type'
  mapping:
    label:
      type: label
      label: 'Name'
    id:
      type: string
      label: 'Machine-readable name'
    description:
      type: text
      label: 'Description'
    aspect_ratio:
      type: string
      label: 'Aspect ratio'
    third_party_settings:
      type: sequence
      label: 'Third party settings'
      sequence:
        type: crop_type.third_party.[%key]

media_entity.bundle.third_party.crop:
  type: mapping
  label: 'Crop settings'
  mapping:
    image_field:
      type: string
      label: 'Field storing image to be cropped'

image.effect.crop_crop:
  type: mapping
  label: 'Crop effect configuration'
  mapping:
    crop_type:
      label: 'Crop type'
      type: string
