entity_browser.browser.widget.dropzonejs:
  type: mapping
  label: 'DropzoneJS widget configuration'
  mapping:
    submit_text:
      type: string
      label: 'Submit button text'
    auto_select:
      type: boolean
      label: 'Automatically submit selection'
    upload_location:
      type: string
      label: 'Upload location'
    dropzone_description:
      type: string
      label: 'Dropzone drag-n-drop zone text'
    max_filesize:
      type: string
      label: 'Maximum size of files'
    extensions:
      type: string
      label: 'Allowed file extensions'
    clientside_resize:
      type: boolean
      label: 'Use clientside resize'
    resize_width:
      type: integer
      label: 'Maximum width'
    resize_height:
      type: integer
      label: 'Maximum height'
    resize_quality:
      type: float
      label: 'Resize quality'
    resize_method:
      type: string
      label: 'Method used for resizing'
    thumbnail_method:
      type: string
      label: 'Method used for generating the thumbnail'

entity_browser.browser.widget.dropzonejs_media_entity:
  type: entity_browser.browser.widget.dropzonejs
  label: 'Media Entity DropzoneJS widget configuration'
  mapping:
    media_entity_bundle:
      type: string
      label: 'Media type'


entity_browser.browser.widget.dropzonejs_media_entity_inline_entity_form:
  type: entity_browser.browser.widget.dropzonejs_media_entity
  label: 'Media Entity DropzoneJS with edit widget configuration'
  mapping:
    form_mode:
      type: string
      label: 'Form mode'
