media_entity.bundle.type.image:
  type: mapping
  label: 'Image type configuration'
  mapping:
    source_field:
      type: string
      label: 'Field with embed code/URL'
    gather_exif:
      type: boolean
      label: 'Gather EXIF metadata'

entity_browser.browser.widget.media_entity_image_upload:
  type: mapping
  label: 'Media images upload widget configuration'
  mapping:
    submit_text:
      type: string
      label: 'Submit button text'
    upload_location:
      type: string
      label: 'Upload location'
    multiple:
      type: boolean
      label: 'Allow multiple uploads'
    extensions:
      type: string
      label: 'Allowed file extensions'
    media_bundle:
      type: string
      label: 'Media bundle for uploaded files'
